### ISSUE TITLE
drop RAML spec or generate server/client server API code from it

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#145]
Currently the RAML spec is just used for documentation purposes, without any connection to the real code. This has given problems<sup>1</sup> and will keep giving problems. Either we should drop it (I wouldn't suggest this, except if we drop it as part of replacing it for something else), or we make sure we can generate both the server and client API code from it. This way, the spec cannot be out of date, given that it is used for the actual code as well. And as both the spec and the code live in the same code repo, it can be tracked together in history.

---

<sup>1</sup> people use the RAML spec to implement alternative (light) clients (e.g. in Python), obviously when the spec is out of date, this causes problems for the implementors, given that their requests will result in unexpected behavior.

**Comment by GlenDC** [comment]
By this point I'm fairly sure we should go for something other than RAML. The only tool that could generate a server front-end and API client would be `go-raml`. However that tool has its flawed and is not actively maintained.

Besides generating that code, we should also generate the daemon API documentation, see #153 for that.

**Comment by lafont-e** [comment]
You were right, there are not a lot of solutions for the raml that I can show to you, and most of the wannabes options lack the support or completeness needed, so they are discarded.

Everything I see at the end points me to OpenAPI/Swagger and go-swagger as generator, there are two more that looks promising but not sure they are for us, Anypoint and WSO2, both are API managers, but I don't see the generator part.

Swagger has big communities and a big number of questions on StackOverflow and the spec file are quite similar to the raml we are used to.

**Comment by GlenDC** [comment]
Fair enough. In that case, please investigate gnostic more seriously (it seems to be the real option I see):

+ be able explain us (the rest of the team) quickly what it can give us, what it is, how it works, etc..;
+ check what work would be required to provide a python plugin (no need to estimate time or really implementation details, as that depends a lot probably on choices we make);
+ play around with the provided golang plugin, and see if that's enough for us to generate golang clients/specs (please just use a small but complex enough spec for this, ideally a provided one);
+ check how we can generate markdown and html documentation from a spec;

**Comment by lafont-e** [comment]
# The case for OpenAPI #

## Introduction ##

We (developers) have been using tools such as RAML as a tool to do API
Management. Ramls has some drawbacks, that the company has tried to address
with tools such as go-raml, but the demise of go-raml, has left the company
with no clear toolset to manage properly the APIs we use and create every day.

So, we looked onto the market to see what other options could provide a
solution to the API management problems we face currently, problems such an
update documentation, or good code generation or even other problems that may
have not arised yet, but surely we will need to address on the future.

As such, we have made a little research to find a good solution for our
current and future problems, OpenAPI emerges from that research as an
industry backed standard able to manage our needs.

OpenAPI is being used and deployed widely by comapnies like Google, Microsoft,
IBM and others. Currently it is being adopted by developers all around the world.

We have evaluated other options, OpenAPI is not the only player in the market,
but the other options or they are propietary (and pricey) or they lack the
maintenance and support we need. Among the most close to our needs are
MuleSoft's Anypoint and Apache's WSO2, a detailed list of API management products
and its position on the market can be found on Gartner's magic quadrant on
enterprise IPaaS (although most of the solutions there are propietary and closed).

## Our needs ##

Out API management needs are few, among the ones we should fullfill are:

* Easy Api Creation, editing and validation
* Good and updated Documentation
* Server Code Generation, initially for Golang and Python
* Good support and maintenance of the tools
* Open Source

OpenApi does all this but not always on a homogeneous tool, but using different
tools from various vendors/developers.

## Tools ##

### Editing ###

The editors make simple the creation of the OpenApi spec file, it's not very
different from the RAML spec we already know, but both editors makes easy to
write correct OpenApi compliants specs. We can use a normal text editor as
always, but sintax and verification are not included.

* [Apicurio studio](http://www.apicur.io/): really like this tools, its simple and
  easy to use, webGUI based, linked to github, and generates the OpenAPI yaml file.
  If you need to start from scratch even knowing little of the specification, this
  tool makes you job easy, also doubles as documentation. It's Java based if not
  used as a web service.

* Swagger editor: the standard reference, text based, ie: you write the YAML, with
  sintax highlighting and autocompletion, also shows the documentaion and let you
  make direct API calls from the browser. Web based.
  It's a web service, java based but can be used locally from the provided docker.

There is also an extension in vscode attached to a swagger editor server, to create
and display the spec file and the documentation.

### Golang generator ###

The generator is maybe the tool we are most interested in as is the one that can
will make most of the API handling.

* gnostic: very promissing, created and used by Google on its systems, modular, so we
  create missing modules we may need. Gnostic is more a protobuff compiler but it has
  a golang generator, and from the code I saw, it is nice, ie: it generates a package
  that comprises the client and the server, the client has a method for every URL
  defined and the server has handlers for all URL and accepts an object that must comply
  with an interface defined in the same package. The code is readable and understable.
  It can generate also standalone versions of the client or server.

  The command needed to generate a scafold for the bookstore sample (the bookstore and
  petsore samples are provided as demo by swagger). Bookstore sample has 4 URL paths,
  2 resources, and security.

  ```bash
  gnostic bookstore.json --PLUGIN-out=bookstore/ --PLUGIN go-generator
  ```

  Among the plugins predefined there is an analyzer used to verify factors that may
  affect the generation of code, statistics and summary of the objects in the spec
  file. I've seen it working, but there are some wrong documentation, as the flags
  used to make it work appears on the info provided but not on the command.

  Also, there is a SWIFT generator, not sure we are going to need it but there is.

  Missing is the python generator, but from the go-generator code seems to be an
  embedded template using go as programming languaje, so if we have clear what
  output we want for the python generator, it does not seem difficult to embedd
  the python template and repeat the same procedure used in golang. Some thinking
  need to be done as the server relies on interfaces and AFAIK python uses classes.

* go-swagger: written as an alternative to swagger codegen, the code generated is way
  more complex, and handlers should be writen on the same files generated. As an
  advantage the server is configured by default to use TLS.

* Swagger codegen, the spec reference generator, it is able to generate code for a
  multitude of languages, but everybody complains about the quality and flatness of
  the code. I took a look at the code generated and is right, it makes the work it
  is supposed to do, but I like way more the one generated by gnostic.

### Python generator ###

From the ones we have reviewed

* Swagger codegen: Explained before, must work well generating python code as I've
  been not able to find other generators.

* pyswagger: a python generator, but only generates clients from the spec file,
  missed the server part, so not really an option.

* go-raml: yes, our old friend, it does not support the OpenAPI spec but there are
  converters between RAML and OpenAPI, so in case of necessity we can convert the
  spec to RAML and go ahead from there. Not a real solution but and alternative.
  Can use the same approach to other RAML python generators.

### Converters ###

The converters are the application that let us migrate old file specs to OpenAPI.

* [api-spec](https://github.com/LucyBot-Inc/api-spec-converter): converts from a
  miriad of formats including RAML, OpenAPI v2 and v3, google and others.

* apimatic.io, multitude of inputs formats to another multitude of output formats,
  it's a WebService.

### Documenters ###

* Spectacle, a nice node app that takes a json file and creates static HTML pages, can
  serve the documentation too.

* openapi-viewer, a web service that takes a json document and present a clean and
  elegant documentation. Allow you to make requests too.

* Swagger Editor, it does present real time documentation of the file being created
  or imported.

* swagger2markup: Java app that converts OpenAPI specs to Markup or AsciiDoc documents,
  it can be combined with hand written ones.
  From AsciiDoc the document can be converted to PDF, ePub, HTML[demo](http://swagger2markup.github.io/spring-swagger2markup-demo/1.1.0/).
  The main drawback is that is difficult to install, act as a library to maven, and
  you need lot of java expertise to have it working.

There are more programs that deals with documenting OpenAPI spec files, but none offers
something more.

I've not found a usable markdown generator. The ones that promise the conversion do not
work, are unmaintained or are unusable.

### Mockers ###

* swagger inspector: from the swagger tool set, it let you make requests and see how the
  api will respond without building the code.

* sportlight: payware (but free for less than 2500 resources), that mocks the behaviour
  of the API.

## Summary ##

After reviewing all the options and tools OpenApi offers, it is a good alternative
when we need to think on changin RAML.

Among the brightest qualities of the OpenAPI specs, I will highlight:

* Industry standad, baked and supported by giants. It has a lot of chances to stay
  and not to be a season trend.

* Great ecosystem, there are multitude of tools for every need, good and poor ones
  but always there is one that fits the bill

* Mostly open source, there is some propietary software too, but I don't consider this a
  drawback, but just another option when something needed is not available as open source.

Specs can be found at [OpenAPI](https://github.com/OAI/OpenAPI-Specification)

**Comment by lafont-e** [comment]
When doing tests with the [rivine api](https://studio.apicur.io/apis/851), the file is right but it's missing the responses bodies, that should be added to every path
```
        responses:
            "200":
              description: Success
            "400":
              description: Failure  
```
Mostly because can not create it from apicur.io, it does not save the responses when added.

gnostic complains with
```
gnostic --go-generator-out=api Rivine.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66204a]

goroutine 1 [running]:
main.(*Renderer).RenderClient(0xc42007bea0, 0x9, 0x7282e1, 0x9, 0x0, 0x7f599da946c8)
	/home/enric/Code/go/src/github.com/googleapis/gnostic/plugins/gnostic-go-generator/render_client.go:113 +0xffa
main.(*Renderer).Render(0xc42007bea0, 0xc4200c4690, 0xc42007bf28, 0x5, 0x5, 0xc4200c2238, 0x0)
	/home/enric/Code/go/src/github.com/googleapis/gnostic/plugins/gnostic-go-generator/renderer.go:45 +0x4b2
main.main()
	/home/enric/Code/go/src/github.com/googleapis/gnostic/plugins/gnostic-go-generator/main.go:66 +0x3d4
Errors reading Rivine.yaml
exit status 2
```

Rivine.yaml is the file downloaded from apicur.io and edited to add the responses body
