### ISSUE TITLE
Node consensus can diverge

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#214]
Running on the tf testnet, one of 3 blockcreators suddenly stopped. After this, the daemon refuses to accept blocks from the other nodes, and instead starts to create his own blocks, thus effectively creating his own chain. Downloading the persistent files and starting a daemon with them locally causes this daemon to sync with the mallfunctioning daemon in question. Stack traces

```go
con.subscribe('15c16ca0-595b-42bb-bd92-e72cdc061fde').stream()
(0/5) Loading daemon of tfchaind...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
(4/5) Loading wallet...
(5/5) Loading block creator...
Finished loading in 0.76071733 seconds
Rescanning consensus set...

Done!
SIGQUIT: quit
PC=0x45a8d3 m=1 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xd96438, 0x0, 0xc420033eb8, 0x0, 0x0, 0xc420033ed0, 0x3c, 0x0, 0xc420033ed0, 0x40fa10, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:480 +0x23
runtime.futexsleep(0xd96438, 0x0, 0xdf8475800)
	/usr/local/go/src/runtime/os_linux.go:62 +0xd7
runtime.notetsleep_internal(0xd96438, 0xdf8475800, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:193 +0x130
runtime.notetsleep(0xd96438, 0xdf8475800, 0xb0e3145c7d201)
	/usr/local/go/src/runtime/lock_futex.go:216 +0x56
runtime.sysmon()
	/usr/local/go/src/runtime/proc.go:3876 +0x14d
runtime.mstart1()
	/usr/local/go/src/runtime/proc.go:1182 +0x11e
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1152 +0x64

goroutine 1 [chan receive, 1600 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon(0x9adf61, 0x8, 0x10100, 0x0, 0xc4200ca7c0, 0x11, 0x7ffcd9b54f47, 0x11, 0x9ab0d0, 0x6, ...)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:375 +0x8e3
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.newStartDaemonCmd.func1(0xc420146d80, 0xc4201a1ce0, 0x0, 0x7)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/commands.go:36 +0x5d
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).execute(0xc420146d80, 0xc42000e090, 0x7, 0x7, 0xc420146d80, 0xc42000e090)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420146d80, 0x0, 0x9c3ec7, 0x30)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420146d80, 0xc42010d108, 0x9ade29)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.SetupDefaultDaemon(0x9adf61, 0x8, 0x10100, 0x0, 0x9a93d8, 0x0, 0x9b212b, 0xf, 0x9ab0d0, 0x6, ...)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/commands.go:167 +0xd08
main.main()
	/go/src/github.com/threefoldfoundation/tfchain/cmd/tfchaind/main.go:20 +0x258

goroutine 4 [syscall, 1600 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 5 [select, 1600 minutes, locked to thread]:
runtime.gopark(0x9d6c10, 0x0, 0x9abeb0, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420036f50, 0xc42006a480)
	/usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 33 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f28e70bc1c8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420208018, 0x72, 0xc420037c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420208018, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420208000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420208000, 0xc420037e58, 0x401137, 0xc4201e0800)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42020c000, 0x752b98, 0x455bf0, 0xc420037ea0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42020c000, 0x9d6618, 0xc4201e0780, 0xcae920, 0xc420232090)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
net/http.(*Server).Serve(0xc42020e000, 0xcadc20, 0xc42020c000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.(*Server).Serve(0xc420206020, 0x1000000010000, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/server.go:332 +0x44
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon.func1(0xc420216000, 0xc420206020)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:205 +0x2b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:204 +0x2e9

goroutine 34 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7f28e70bc108, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420208098, 0x72, 0xc42036fd00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420208098, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420208080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420208080, 0x46e966, 0x486948, 0xc420515bc8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42020c030, 0x43ab2f, 0xc42036fee8, 0x84ea7b)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42020c030, 0x0, 0x0, 0x0, 0xc420104020)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentListen(0xc420058300, 0xc420216120)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:96 +0x75
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.New
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:299 +0xb59

goroutine 35 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedSleep(0xc420058300, 0x12a05f200, 0xc420240000)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:173 +0x109
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentPeerManager(0xc420058300, 0xc420216180)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peersmanager.go:139 +0x5ab
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.New
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:306 +0xbfd

goroutine 36 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentNodeManager(0xc420058300, 0xc4202161e0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/nodes.go:241 +0x166
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.New
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:313 +0xca1

goroutine 37 [select, 2 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentNodePurger(0xc420058300, 0xc420216240)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/nodes.go:178 +0x1ca
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.New
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:320 +0xd45

goroutine 349 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc42000e180)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 351 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc42000e180, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc42000e180, 0xc42003cec8, 0x8542f1, 0x455bf0, 0xc42003cf08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc420218d40, 0x9d61b0, 0xc420058300, 0xcb1c40, 0xc420333bc0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc420058300, 0xc420218d40)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 20 [sleep]:
time.Sleep(0x1dcd65000)
	/usr/local/go/src/runtime/time.go:65 +0x130
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc4202b23c0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:50 +0x151
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.New
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:133 +0x50d

goroutine 21 [chan receive, 1600 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon.func9(0xc4201ee8a0, 0xc420206020)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:366 +0x38
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:365 +0x767

goroutine 350 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc42000e180)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 488 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc42000e280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 78 [select, 1600 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc420216660, 0xc420058300, 0xc4202166c0, 0xc42023f000)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 90 [IO wait]:
internal/poll.runtime_pollWait(0x7f28e70bbec8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420208518, 0x72, 0xffffffffffffff00, 0xcaa0e0, 0xca53f8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420208518, 0xc420378000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420208500, 0xc420378000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420208500, 0xc420378000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420104018, 0xc420378000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f28e71050b0, 0xc420104018, 0xc420378000, 0x8, 0x10008, 0x8, 0x98cc60, 0x0, 0x7f28e71050b0)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f28e71050b0, 0xc420104018, 0xc420378000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420208580, 0xc420378000, 0x10008, 0x10008, 0x10301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420208580)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 91 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420208580)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 92 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420208580)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 93 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420208580, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420208580, 0xc420371ec8, 0x8542f1, 0x455bf0, 0xc420371f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc42023f000, 0x9d61b0, 0xc420058300, 0xcb1c40, 0xc4202a8760)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc420058300, 0xc42023f000)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 487 [IO wait]:
internal/poll.runtime_pollWait(0x7f28e70bbf88, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42000e218, 0x72, 0xffffffffffffff00, 0xcaa0e0, 0xca53f8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42000e218, 0xc4203f4000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42000e200, 0xc4203f4000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42000e200, 0xc4203f4000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42020c070, 0xc4203f4000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f28e71050b0, 0xc42020c070, 0xc4203f4000, 0x8, 0x10008, 0x8, 0x98cc60, 0x0, 0x7f28e71050b0)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f28e71050b0, 0xc42020c070, 0xc4203f4000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc42000e280, 0xc4203f4000, 0x10008, 0x10008, 0x10301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc42000e280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 348 [IO wait]:
internal/poll.runtime_pollWait(0x7f28e70bc048, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42000e118, 0x72, 0xffffffffffffff00, 0xcaa0e0, 0xca53f8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42000e118, 0xc420458000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42000e100, 0xc420458000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42000e100, 0xc420458000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c070, 0xc420458000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f28e71050b0, 0xc42000c070, 0xc420458000, 0x8, 0x10008, 0x8, 0x98cc60, 0x0, 0x7f28e71050b0)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f28e71050b0, 0xc42000c070, 0xc420458000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc42000e180, 0xc420458000, 0x10008, 0x10008, 0x403300010100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc42000e180)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 364 [select, 1588 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc42006ac00, 0xc420058300, 0xc42006ac60, 0xc420218d40)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 489 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc42000e280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 490 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc42000e280, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc42000e280, 0xc4203a1ec8, 0x8542f1, 0x455bf0, 0xc4203a1f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc420049700, 0x9d61b0, 0xc420058300, 0xcb1c40, 0xc4203326c0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc420058300, 0xc420049700)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 455 [select, 1584 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc420240720, 0xc420058300, 0xc420240780, 0xc420049700)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

rax    0xfffffffffffffffc
rbx    0x0
rcx    0x45a8d3
rdx    0x0
rdi    0xd96438
rsi    0x0
rbp    0xc420033ec8
rsp    0xc420033e80
r8     0x0
r9     0x0
r10    0xc420033eb8
r11    0x246
r12    0x42f3c0
r13    0xf1
r14    0x11
r15    0x0
rip    0x45a8d3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by LeeSmet** [comment]
The issue seems to reproduce consistently when 2 nodes talk to each other which at some point have forked. When the "trailing" node receives blocks from the "leading" node (which are not yet on the longest fork of the trailing node), the `checkTarget` function can fail as the received block does not meet the required target. This causes the block to be rejected rather than maintained on the short fork. As a result, the short fork can't continue to extend, thus creating an effective fork in the chain, even though both nodes continue to talk in the same network.

It seems that the check receives a wrong target to match the new block against.
