### ISSUE TITLE
testnet nodes frozen

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#234]
```


io.ReadFull(0x7f89c43990c8, 0xc420208008, 0xc42029a000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420238100, 0xc42029a000, 0x10008, 0x10008, 0x10301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420238100)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 37 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420238100)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 38 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420238100)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 39 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420238100, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420238100, 0xc420230ec8, 0x855351, 0x455bf0, 0xc420230f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc4201f0300, 0x9d8010, 0xc42011c840, 0xcb4c20, 0xc420416f00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc4201f0300)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 19 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc42028c0c0, 0xc42011c840, 0xc42028c120, 0xc4201f0300)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 40 [chan receive, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon.func9(0xc4201e05a0, 0xc420082dc0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:411 +0x38
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:410 +0x988

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f89c43ddd30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420262198, 0x72, 0xffffffffffffff00, 0xcad0c0, 0xca83e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420262198, 0xc420356000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420262180, 0xc420356000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420262180, 0xc420356000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420212020, 0xc420356000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f89c43990c8, 0xc420212020, 0xc420356000, 0x8, 0x10008, 0x8, 0x98e4e0, 0x0, 0x7f89c43990c8)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f89c43990c8, 0xc420212020, 0xc420356000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420262200, 0xc420356000, 0x10008, 0x10008, 0x6c900010100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420262200)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 22 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420262200)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 23 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420262200)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 24 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420262200, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420262200, 0xc4201e8ec8, 0x855351, 0x455bf0, 0xc4201e8f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc42020a3c0, 0x9d8010, 0xc42011c840, 0xcb4c20, 0xc4206d1d20)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc42020a3c0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 67 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc420057140, 0xc42011c840, 0xc4200571a0, 0xc42020a3c0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 58 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc42028c000, 0xc42011c840, 0xc42028c180, 0xc42020a940)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 75 [IO wait]:
internal/poll.runtime_pollWait(0x7f89c43dda30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42007e818, 0x72, 0xffffffffffffff00, 0xcad0c0, 0xca83e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42007e818, 0xc4203fa000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42007e800, 0xc4203fa000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42007e800, 0xc4203fa000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420212048, 0xc4203fa000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f89c43990c8, 0xc420212048, 0xc4203fa000, 0x8, 0x10008, 0x8, 0x98e4e0, 0x0, 0x7f89c43990c8)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f89c43990c8, 0xc420212048, 0xc4203fa000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc42007e880, 0xc4203fa000, 0x10008, 0x10008, 0x10301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc42007e880)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 89 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc42028ca80, 0xc42011c840, 0xc42028cae0, 0xc420049b00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 76 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc42007e880)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 77 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc42007e880)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 78 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc42007e880, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc42007e880, 0xc4203d46c8, 0x85519a, 0x455bf0, 0xc4203d4708)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc420049b00, 0x9d8020, 0xc42028ca80, 0xc42011c840, 0xc42028cae0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc420049b00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 160 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc420056120, 0xc42011c840, 0xc420056180, 0xc42022f000)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 123 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420238800)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 109 [IO wait]:
internal/poll.runtime_pollWait(0x7f89c43dd7f0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420238218, 0x72, 0xffffffffffffff00, 0xcad0c0, 0xca83e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420238218, 0xc420534000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420238200, 0xc420534000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420238200, 0xc420534000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c0c0, 0xc420534000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f89c43990c8, 0xc42000c0c0, 0xc420534000, 0x8, 0x10008, 0x8, 0x98e4e0, 0x0, 0x7f89c43990c8)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f89c43990c8, 0xc42000c0c0, 0xc420534000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420238280, 0xc420534000, 0x10008, 0x10008, 0x10301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420238280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 110 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420238280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 111 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420238280)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 112 [select, 238 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420238280, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420238280, 0xc4202d1ec8, 0x855351, 0x455bf0, 0xc4202d1f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc42020a940, 0x9d8010, 0xc42011c840, 0xcb4c20, 0xc4200e1460)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc42020a940)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 122 [IO wait]:
internal/poll.runtime_pollWait(0x7f89c43dd730, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420238798, 0x72, 0xffffffffffffff00, 0xcad0c0, 0xca83e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420238798, 0xc420624000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420238780, 0xc420624000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420238780, 0xc420624000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420212538, 0xc420624000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f89c43990c8, 0xc420212538, 0xc420624000, 0x8, 0x10008, 0x8, 0x98e4e0, 0x0, 0x7f89c43990c8)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f89c43990c8, 0xc420212538, 0xc420624000, 0x8, 0x10008, 0x7fd2cc, 0x1, 0xc420397e78)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420238800, 0xc420624000, 0x10008, 0x10008, 0x89c00010101, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420238800)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 124 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420238800)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

goroutine 125 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420238800, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420238800, 0xc4202d3ec8, 0x855351, 0x455bf0, 0xc4202d3f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc42022f000, 0x9d8010, 0xc42011c840, 0xcb4c20, 0xc4204401c0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc42022f000)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 4653 [select, 152 minutes]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer.func1(0xc42063cd20, 0xc42011c840, 0xc42063cd80, 0xc42020a200)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:144 +0x127
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:138 +0x10a

goroutine 4635 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).sendLoop(0xc420238c00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 4634 [IO wait]:
internal/poll.runtime_pollWait(0x7f89c43dd670, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420238b98, 0x72, 0xffffffffffffff00, 0xcad0c0, 0xca83e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420238b98, 0xc42049c000, 0x8, 0x10008)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420238b80, 0xc42049c000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420238b80, 0xc42049c000, 0x8, 0x10008, 0x8, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c080, 0xc42049c000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f89c43990c8, 0xc42000c080, 0xc42049c000, 0x8, 0x10008, 0x8, 0x98e4e0, 0x0, 0x7f89c43990c8)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7f89c43990c8, 0xc42000c080, 0xc42049c000, 0x8, 0x10008, 0x7fd2cc, 0x0, 0xc4202dfe78)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).readFrame(0xc420238c00, 0xc42049c000, 0x10008, 0x10008, 0xbd500010101, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:213 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).recvLoop(0xc420238c00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 4637 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).AcceptStream(0xc420238c00, 0x0, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:125 +0x260
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.smuxSession.Accept(0xc420238c00, 0xc4201e6ec8, 0x855351, 0x455bf0, 0xc4201e6f08)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/stream.go:24 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*peer).accept(0xc42020a200, 0x9d8010, 0xc42011c840, 0xcb4c20, 0xc4204404e0)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:57 +0x38
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).threadedListenPeer(0xc42011c840, 0xc42020a200)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:159 +0x11b
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).addPeer
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:68 +0x96

goroutine 4636 [select]:
github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.(*Session).keepalive(0xc420238c00)
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux.newSession
	/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/xtaci/smux/session.go:78 +0x219

rax    0xfffffffffffffffc
rbx    0x0
rcx    0x45a8d3
rdx    0x0
rdi    0xd99278
rsi    0x0
rbp    0xc420033ec8
rsp    0xc420033e80
r8     0x0
r9     0x0
r10    0xc420033eb8
r11    0x246
r12    0x42f3c0
r13    0xf1
r14    0x11
r15    0x0
rip    0x45a8d3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by LeeSmet** [comment]
Part of one of the stacktraces since the terminal buffer could not handle it

**Comment by LeeSmet** [comment]
Nodes sat there, refused to accept any new connection even though they only had 4 active connections, did not make any new blocks for the last 3-4 hours

**Comment by GlenDC** [comment]
Please verify if this is still an active issue.
