### ISSUE TITLE
Fork recovery occasionally fails

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#267]
In a network with more than 1 block creator, it is possible that a fork occurs. Normally this fork should be resolved automatically, though this is not always the case (not for all nodes at least). It seems that the validation function for new blocks always looks at the current fork of the node. Therefore if the new block (on another fork) is validated, the ubso ID is possibly wrong, causing the block to be rejected and the fork to not be accepted on this node

**Comment by LeeSmet** [comment]
It seems that I managed to fix the root cause of the problem, yet there is an inexplicable deadlock now for some reason. It is not really consistent when it happens

**Comment by GlenDC** [comment]
Is this deadlock only because of your fix, or was it already there?

**Comment by LeeSmet** [comment]
I suppose its caused by my fix, but I don't see how as I didn't do anything with locks. Looking into it atm.

**Comment by LeeSmet** [comment]
On further investigation, it seems that the problem is caused by a debug check (see attached stack trace). Its also not a deadlock in itself, the (write)lock is just held for a very long time, causing other goroutines to sit there and wait for the lock, giving a deadlock like impression

```
goroutine 57 [runnable]:
github.com/threefoldfoundation/tfchain/vendor/golang.org/x/crypto/blake2b.(*digest).Sum(0xc42030d500, 0x0, 0x0, 0x0, 0x20, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/golang.org/x/crypto/blake2b/blake2b.go:201 +0x130
github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree.sum(0xc44f00, 0xc42030d500, 0xc42041c348, 0x3, 0x3, 0xcb8bb6476e1579ac, 0xc4210bc120, 0xc42041c388)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree/tree.go:55 +0xd5
github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree.nodeSum(0xc44f00, 0xc42030d500, 0xc4210bc100, 0x20, 0x20, 0xc4210bc120, 0x20, 0x20, 0x20, 0xc4210bc120, ...)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree/tree.go:69 +0x177
github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree.joinSubTrees(0xc44f00, 0xc42030d500, 0xc420cf2150, 0xc420cf2180, 0x20)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree/tree.go:86 +0x13b
github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree.(*Tree).Push(0xc420170690, 0x7fbb463814c0, 0x20, 0x20)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/NebulousLabs/merkletree/tree.go:222 +0x394
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.consensusChecksum.func1(0x7fbb463814b8, 0x8, 0x8, 0x7fbb463814c0, 0x20, 0x20, 0x20, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consistency.go:44 +0x97
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt.(*Bucket).ForEach(0xc4200ad800, 0xc42041c6a8, 0x11, 0x11)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt/bucket.go:361 +0x22a
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.consensusChecksum(0xc420551ce0, 0x0, 0x0, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consistency.go:42 +0x26c
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).generateAndApplyDiff(0xc420047800, 0xc420551ce0, 0xc420cf6500, 0x16, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/diffs.go:179 +0x4a9
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc420047800, 0xc420551ce0, 0xc42033cc80, 0x6, 0x0, 0x0, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/fork.go:90 +0x573
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).forkBlockchain(0xc420047800, 0xc420551ce0, 0xc42033cc80, 0xf, 0x0, 0x0, 0x8c86c514bd4e5d01, 0x5acba065, 0xeee, 0x0, ...)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/fork.go:123 +0x21d
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree.func1(0xc420551ce0, 0xbe4ec0, 0xc420551ce0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:157 +0x394
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt.(*DB).Update(0xc4202e41e0, 0xc42041ce98, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt/db.go:595 +0xb5
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree(0xc420047800, 0x69827407a99cb882, 0xf678a78c5cc210a3, 0x1214a5c228bc37dd, 0x8c86c514bd4e5d62, 0x5acba065, 0xeee, 0x0, 0x0, 0xc4200aa780, ...)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:137 +0x187
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc420047800, 0x69827407a99cb882, 0xf678a78c5cc210a3, 0x1214a5c228bc37dd, 0x8c86c514bd4e5d62, 0x5acba065, 0xeee, 0x0, 0x0, 0xc4200aa780, ...)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:262 +0x30c
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420047800, 0xc47340, 0xc42046e200, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:220 +0x492
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).(github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.managedReceiveBlocks)-fm(0xc47340, 0xc42046e200, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:397 +0x56
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedRPC(0xc4202b4000, 0xc4202d8100, 0x13, 0xbbbe6b, 0xa, 0xc42024a010, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:66 +0x35e
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).RPC(0xc4202b4000, 0xc4202d8100, 0x13, 0xbbbe6b, 0xa, 0xc42024a010, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:76 +0xd2
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420047800, 0xc42041deb8, 0xc42041de40, 0xc42041de48, 0x0, 0x0)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:528 +0x197
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420047800, 0xc4202df728, 0x484a90)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:549 +0x1dd
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New.func1(0x1, 0xc420047800, 0xc420058150, 0xc48540, 0xc4202b4000)
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:171 +0x539
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New
	/home/lee/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:164 +0x1275
```
