### ISSUE TITLE
Crash on consistency check

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#3]
```sh
panic: Wrong number of coins: 960000000000000000000000000
total: 960000000000000000000000000
expected: 0
 expected is bigger: 960000000000000000000000000

goroutine 16 [running]:
panic(0x48f180, 0xc420310340)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rivine/rivine/modules/consensus.manageErr(0xc42029ad20, 0x777460, 0xc420310340)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:20 +0x5b
github.com/rivine/rivine/modules/consensus.checkCoinCount(0xc42029ad20)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:104 +0x5c7
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).checkConsistency(0xc420170480, 0xc42029ad20)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:170 +0x42
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).maybeCheckConsistency(0xc420170480, 0xc42029ad20)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:188 +0x6a
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc420170480, 0xc42029ad20, 0xc420126240, 0x0, 0x0, 0x0, 0x8eb96e47e17c0700, 0x454ba6932ae23b6b)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/fork.go:98 +0x16f
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).forkBlockchain(0xc420170480, 0xc42029ad20, 0xc420126240, 0x5c78c5185eaf4884, 0x95a93fcd76d705c6, 0x18af8b3c3c019717, 0x95b4e9b21aede0ab, 0xa2, 0x1, 0x1, ...)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/fork.go:111 +0xac
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree.func1(0xc42029ad20, 0x574a30, 0xc42029ad20)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/accept.go:153 +0x19b
github.com/rivine/rivine/vendor/github.com/NebulousLabs/bolt.(*DB).Update(0xc42010e960, 0xc42051da60, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/vendor/github.com/NebulousLabs/bolt/db.go:595 +0xb5
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree(0xc420170480, 0x5c78c5185eaf4884, 0x95a93fcd76d705c6, 0x18af8b3c3c019717, 0x95b4e9b21aede0ab, 0xa2, 0x1, 0x1, 0x5806216d, 0x0, ...)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/accept.go:177 +0xe9
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc420170480, 0x5c78c5185eaf4884, 0x95a93fcd76d705c6, 0x18af8b3c3c019717, 0x95b4e9b21aede0ab, 0xa2, 0x1, 0x1, 0x5806216d, 0x0, ...)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/accept.go:254 +0x184
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).AcceptBlock(0xc420170480, 0x5c78c5185eaf4884, 0x95a93fcd76d705c6, 0x18af8b3c3c019717, 0x95b4e9b21aede0ab, 0xa2, 0x1, 0x1, 0x5806216d, 0x0, ...)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/consensus/accept.go:287 +0x10c
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc42015b0e0, 0x5c78c5185eaf4884, 0x95a93fcd76d705c6, 0x18af8b3c3c019717, 0x95b4e9b21aede0ab, 0xa2, 0x1, 0x1, 0x5806216d, 0x0, ...)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/blockcreator/blockmanager.go:16 +0x107
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc42015b0e0)
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:34 +0x288
created by github.com/rivine/rivine/modules/blockcreator.New
	/Users/rob/workspace/go/src/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:126 +0x469
```

**Comment by robvanmieghem** [comment]
https://github.com/rivine/rivine/commit/48a2b0460af70945c4cced4bd28e536a61f0eb05
