### ISSUE TITLE
"Critical error: explorer update failed: database not open" after running "tfchainc stop"

### ISSUE THREAD

**Issue by konceptzer0** [rivine/rivine#391]
Wanting to update from v1.0.5 atomicswap patched to v1.0.6, I ran the "tfchainc stop" cmd and instantly got a non stop flood of error messages identical to this one:

```

goroutine 52 [running]:
runtime/debug.Stack(0x445147, 0x0, 0xc4201dadd8)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go-1.10/src/runtime/debug/stack.go:16 +0x22
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build.Critical(0xc4201dae80, 0x2, 0x2)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build/critical.go:15 +0x93
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer.(*Explorer).ProcessConsensusChange(0xc420183680, 0x4fc36ba43814b0eb, 0x59b588172c31e443, 0xc6786f277ea7d9fd, 0x8dccf8bbaaa22644, 0x0, 0x0, 0x0, 0xc420b525b0, 0x1, ...)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer/update.go:204 +0xd4
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc420089400, 0x0, 0x0, 0x0, 0xc4218f7120, 0x1, 0x1)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:85 +0x171
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc420089400, 0x751ab33bfa3df499, 0x2923a360a25b4ede, 0xebea76c6ac5b8870, 0xc6a09e9d63495d0e, 0x5adf69b9, 0x3afb, 0x0, 0x0, 0xc4203d2280, ...)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:268 +0x234
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420089400, 0x9bb120, 0xc4203614a0, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:220 +0x3c2
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).(github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.managedReceiveBlocks)-fm(0x9bb120, 0xc4203614a0, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:397 +0x3e
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedRPC(0xc420260000, 0xc420022140, 0x13, 0x94dcb5, 0xa, 0xc42029cbc0, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:66 +0x2ab
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).RPC(0xc420260000, 0xc420022140, 0x13, 0x94dcb5, 0xa, 0xc42029cbc0, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:76 +0xc4
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420089400, 0xc4201dbf18, 0xc4201dbec0, 0xc4201dbec8, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:527 +0x118
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420089400, 0x0, 0x0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:548 +0x14a
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New.func1(0x1, 0xc420089400, 0xc42029c170, 0x9bbbc0, 0xc420260000)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:171 +0x373
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:164 +0xb65
Critical error: explorer update failed: database not open
Please submit a bug report here: https://github.com/rivine/rivine/issues

```

CTRL+C didn't do anything,
Ran "pkill tfchaind" to stop the message flood in the terminal

**Comment by LeeSmet** [comment]
Problem is that the explorer module does not unsubscribe from the `cs` after calling close on it, but does call close on the db. As a result, the `cs` keeps pushing updates to the explorer module which tries to write to the closed db file, thus giving the errors. As for the fact that they keep flooding, this likely happened during the IBD phase, which had a bug in this version that prevents the interuption of IBD with just `ctrl+C`. That bug has meanwhile been fixed in #74
