### ISSUE TITLE
mutex lock when trying to sync new node

### ISSUE THREAD

**Issue by nvinken** [rivine/rivine#44]
How I get to a locked node while syncing

I have a node with 11000 ish blocks
I create a new node (HW) with clean setup (no folders) and generate a new wallet
I added the allready generating nodes address to the gateway list of the new node.
All well when syncing for around 1600 blocks (is not specific)
Then there is a double lock:

Last part of the rivined debug:

```
t.CoinOutputSum()
0
Demote5041975 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 261 true
!Lock5298963 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 21 true
Demote5300958 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 115 true
DemotedUnlock5301004 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 117 true
DemotedUnlock5042158 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 266 true
!Lock5041384 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 200 true
inputSum
0
t.CoinOutputSum()
0
Demote5041975 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 261 true
!Lock5298963 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 21 true
Demote5300958 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 115 true
DemotedUnlock5301004 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 117 true
DemotedUnlock5042158 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 266 true
!Lock5041384 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 200 true
inputSum
0
t.CoinOutputSum()
0
Demote5041975 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 261 true
!Lock5298963 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 21 true
Demote5300958 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 115 true
DemotedUnlock5301004 /home/niko/go/src/github.com/rivine/rivine/modules/transactionpool/update.go 117 true
DemotedUnlock5042158 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 266 true
!Lock5041384 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/accept.go 200 true
inputSum
0
t.CoinOutputSum()
0
RLock5138726 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go 182 true
RLock5074045 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go 270 true
RLock5074045 /home/niko/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go 270 true
```

The prints are done in demotemutex.go but its printing -1 of the stack its on, so printing the place where the mutex lock is called.

When killing the deamon and restarting, It went till the last block and keep synced.

**Comment by LeeSmet** [comment]
For now I'll take a quick look to see if I can easily pinpoint the problem. If not, then this will probably surface again in the test network with more reliable/up to date info

**Comment by GlenDC** [comment]
@nvinken seemed to bump into this one easily, so hopefully you can pinpoint it. Fairly sure that Sia has fixed quite some deadlocks already though, some on purpose, while others by accident. We should probably start merging stuff over slowly but surely, as it might fix some bugs (perhaps including this one).

**Comment by LeeSmet** [comment]
It seems that i can reproduce this by forcing a call to `checkConsistency`. Because of another bug (#61), this call eventually starts a panic (in debug builds), which seems to be the culprit. 

```

goroutine 26 [semacquire]:
sync.runtime_Semacquire(0xc4202221b4)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc4202221a8)
	/usr/local/go/src/sync/rwmutex.go:50 +0x95
github.com/rivine/rivine/vendor/github.com/NebulousLabs/demotemutex.(*DemoteMutex).RLock(0xc4202221a0)
	/home/lee/go/src/github.com/rivine/rivine/vendor/github.com/NebulousLabs/demotemutex/demotemutex.go:42 +0x3f
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks.func3(0xc420222000, 0xc4203f9217)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:182 +0x65
panic(0xb4aaa0, 0xc4201a4170)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/rivine/rivine/modules/consensus.manageErr(0xc42035e2a0, 0xf3ca00, 0xc4201a4170)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:20 +0x6c
github.com/rivine/rivine/modules/consensus.checkCoinCount(0xc42035e2a0, 0xa)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:110 +0x843
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).checkConsistency(0xc420222000, 0xc42035e2a0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:176 +0x9f
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).maybeCheckConsistency(0xc420222000, 0xc42035e2a0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consistency.go:194 +0x7c
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree.func1(0xc42035e2a0, 0xc1dc08, 0xc42035e2a0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/accept.go:142 +0x12b
github.com/rivine/rivine/vendor/github.com/NebulousLabs/bolt.(*DB).Update(0xc4201f21e0, 0xc4203f8f28, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/vendor/github.com/NebulousLabs/bolt/db.go:595 +0xc2
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).addBlockToTree(0xc420222000, 0x453f489db813076c, 0x33453e65533e9638, 0xea683f259c72862f, 0xa921b66e865e4da7, 0x5a7887ca, 0xa, 0x0, 0x0, 0xc4201f1140, ...)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/accept.go:136 +0x191
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc420222000, 0x453f489db813076c, 0x33453e65533e9638, 0xea683f259c72862f, 0xa921b66e865e4da7, 0x5a7887ca, 0xa, 0x0, 0x0, 0xc4201f1140, ...)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/accept.go:252 +0x1df
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420222000, 0xf46cc0, 0xc42021c4c0, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:212 +0x4b2
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).(github.com/rivine/rivine/modules/consensus.managedReceiveBlocks)-fm(0xf46cc0, 0xc42021c4c0, 0xb606c0, 0xc4202402e0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:389 +0x56
github.com/rivine/rivine/modules/gateway.(*Gateway).managedRPC(0xc4201ba420, 0xc42019db20, 0x10, 0xbf7d06, 0xa, 0xc4202042b0, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/modules/gateway/rpc.go:57 +0x28b
github.com/rivine/rivine/modules/gateway.(*Gateway).RPC(0xc4201ba420, 0xc42019db20, 0x10, 0xbf7d06, 0xa, 0xc4202042b0, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/modules/gateway/rpc.go:67 +0xdf
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420222000, 0xc4203f9eb8, 0xc4203f9e28, 0xc4203f9e30, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:520 +0x1b0
github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420222000, 0x0, 0x0)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:546 +0x1e0
github.com/rivine/rivine/modules/consensus.New.func1(0x1, 0xc4201a42d0, 0xc420222000, 0xf46f40, 0xc4201ba420)
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go:155 +0x59b
created by github.com/rivine/rivine/modules/consensus.New
	/home/lee/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go:148 +0xf26
```

Note that no panic message seems to be written to the terminal where the daemon was started

**Comment by LeeSmet** [comment]
It seems like this (https://github.com/rivine/rivine/blob/master/modules/consensus/accept.go#L200) is the offending lock, deeper in the callstack it *might* call `checkConsistency`, which currently fails due to another bug. Upon failure in debug mode, causing the lock to never unlock. Running a non debug build indeed prints the error without locking up

**Comment by LeeSmet** [comment]
After fixing #61, it seems like this is probably not related after all, so the root cause will need to be examined again

**Comment by LeeSmet** [comment]
I seem to be unable to reproduce this bug at the moment (building from master), so I'll just let this rest for now.

**Comment by robvanmieghem** [comment]
unable to reproduce for now
